姓名：天上人间
url：https：//xiaohang007.github.io/：//xiaohang007.github.io/

：[排除：[ bibble，readme.md，makefile，screenshot.png ]，readme.md，makefile，screenshot.png ]  [排除：[ bibble：[bibble：[bibble： [bibble，readme readme.mdeme.md ,, md ,, md ,, readme.md ,, md ,, makefile ,, makefile ,, makefile ,, ,, ,, ,, ,, ,, ,, ,, ,, ,, ,, ,,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  , ,  ,， ScreenShot.png这是给出的

＃用 py
荧光笔：荧光笔：碎屑

＃博客文章的路径结构。
：永久链接：/博客/：年：月份/：日：日：日：日：日：日：日：日：日：日：日：
编码：编码：UTF-8
＃“人”页面上的部分。
角色：
  -写：教师：教师：教师：教师：教师：教师：教师：教师：教师：教师：教师：教师：教师：教师
    名称：名称：教师教师
  -写：毕业：毕业：毕业：毕业：毕业：毕业：毕业：毕业：毕业：毕业：毕业：毕业：毕业：毕业
    名称：姓名：研究生研究生
  -钥匙： - 钥匙：乌格拉德
    名称：姓名：本科生本科生
  -写：合作：合作：合作：合作：合作：合作：合作：合作：合作：合作：合作：合作：合作：合作
    名称：名称：合作者合作者


＃首页上的新闻报道数量。
Front_page_news：8

＃链接的基本路径名。
根据：'' '

＃为 _projects文件夹制作页面
收藏：
  项目：
    输出：正确

＃导航栏链接。
导航：
  -   标题：主页主页efwe
    关联： /
  -   标题：研究edwwe
    链接： /research.html
  -   标题：论文出版物few
    链接： /publications.html
